import { useState } from "react";
import type { PreHospitalNotification, PatientRecord } from "../types";

const API_BASE = import.meta.env.VITE_API_BASE_URL ?? "http://localhost:8000";

interface EmailDraft {
  to: string;
  subject: string;
  body: string;
}

function buildEmailDraft(notif: PreHospitalNotification, patient?: PatientRecord): EmailDraft {
  const to = "semathew@andrew.cmu.edu"; // charge nurse alias — demo
  const subject = `⚠ INCOMING ${notif.triage_category} PATIENT - ETA ${notif.eta_minutes}min | ${notif.hospital_name}`;

  const vitalsSection = patient
    ? `--- PATIENT VITALS ---
GCS: ${patient.vitals.gcs ?? "Unknown"}
Resp Rate: ${patient.vitals.resp_rate ?? "Unknown"} /min
Radial Pulse: ${patient.vitals.radial_pulse == null ? "Unknown" : patient.vitals.radial_pulse ? "Present" : "ABSENT"}
Special Flags: ${patient.special_flags.join(", ") || "None"}
Needs: ${patient.needs.join(", ") || "General care"}
`
    : "";

  const body = `FIELDOPS AI — PRE-HOSPITAL NOTIFICATION
Generated: T+${notif.minute}min | ${new Date(notif.timestamp).toLocaleTimeString()}

INCOMING PATIENT ALERT
======================
Triage Category : ${notif.triage_category}
Ambulance Unit  : ${notif.ambulance_id}
Patient ID      : ${notif.patient_id}
ETA to Your ED  : ${notif.eta_minutes} minutes

CLINICAL ALERT
--------------
${notif.alert_message}

${vitalsSection}
PREPARATION REQUIRED
--------------------
${notif.prep_needed.length > 0 ? notif.prep_needed.map((p) => `• ${p.replace(/_/g, " ")}`).join("\n") : "• Standard trauma bay setup"}

---
This notification was generated by FieldOps AI (Gemini + LlamaIndex).
Confirm receipt with the dispatching unit on radio channel 4.
Do NOT reply to this email — contact dispatch directly.
`;

  return { to, subject, body };
}

interface PreNotifCardProps {
  notif: PreHospitalNotification;
  patient?: PatientRecord;
}

export function PreNotifCard({ notif, patient }: PreNotifCardProps) {
  const [showModal, setShowModal] = useState(false);
  const [sending, setSending] = useState(false);
  const [sent, setSent] = useState(false);
  const [sentMode, setSentMode] = useState<"sent" | "draft" | null>(null);

  const triageColor =
    notif.triage_category === "RED" ? "#ef4444" :
    notif.triage_category === "YELLOW" ? "#f59e0b" :
    "#10b981";

  const draft = buildEmailDraft(notif, patient);

  async function handleSend() {
    setSending(true);
    try {
      const res = await fetch(`${API_BASE}/api/notify/email`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          notification_id: notif.notification_id,
          recipient_email: draft.to,
          subject: draft.subject,
          body: draft.body,
        }),
      });
      const data = await res.json();
      setSentMode(data.mode === "sent" ? "sent" : "draft");
      setSent(true);
      setTimeout(() => setShowModal(false), 2000);
    } catch {
      setSentMode("draft");
      setSent(true);
    } finally {
      setSending(false);
    }
  }

  return (
    <>
      <div className="prenotif-card-v2" style={{ borderLeftColor: triageColor }}>
        <div className="prenotif-v2-header">
          <span className="prenotif-v2-badge" style={{ background: triageColor, boxShadow: `0 0 8px ${triageColor}88` }}>
            {notif.triage_category}
          </span>
          <span className="prenotif-v2-hospital">{notif.hospital_name}</span>
          <span className="prenotif-v2-eta" style={{ color: triageColor === "#ef4444" ? "#fca5a5" : "#fcd34d" }}>
            ETA {notif.eta_minutes}min
          </span>
          <span className="prenotif-v2-time">T+{String(notif.minute).padStart(2, "0")}</span>
        </div>

        <p className="prenotif-v2-message">{notif.alert_message}</p>

        {notif.prep_needed.length > 0 && (
          <div className="prenotif-v2-prep">
            {notif.prep_needed.map((item) => (
              <span key={item} className="prep-tag-v2">{item.replace(/_/g, " ")}</span>
            ))}
          </div>
        )}

        <div className="prenotif-v2-footer">
          <div className="prenotif-v2-ids">
            <span className="notif-id-pill">{notif.ambulance_id}</span>
            <span className="notif-id-pill">{notif.patient_id}</span>
          </div>
          {sent ? (
            <span className="sent-confirm" style={{ color: sentMode === "sent" ? "#10b981" : "#f59e0b" }}>
              {sentMode === "sent" ? "✓ Email Sent" : "✓ Draft Saved"}
            </span>
          ) : (
            <button className="draft-email-btn" onClick={() => setShowModal(true)}>
              Draft Email
            </button>
          )}
        </div>
      </div>

      {showModal && (
        <div className="email-modal-overlay" onClick={(e) => { if (e.target === e.currentTarget) setShowModal(false); }}>
          <div className="email-modal">
            <div className="email-modal-header">
              <div className="email-modal-title">
                <span className="email-modal-icon">✉</span>
                Pre-Hospital Notification Email
              </div>
              <button className="email-modal-close" onClick={() => setShowModal(false)}>✕</button>
            </div>

            <div className="email-field">
              <label className="email-label">To</label>
              <div className="email-value email-to">{draft.to}</div>
            </div>

            <div className="email-field">
              <label className="email-label">Subject</label>
              <div className="email-value email-subject">{draft.subject}</div>
            </div>

            <div className="email-field email-body-field">
              <label className="email-label">Body</label>
              <pre className="email-body">{draft.body}</pre>
            </div>

            <div className="email-modal-actions">
              <button className="email-cancel-btn" onClick={() => setShowModal(false)}>Cancel</button>
              <button
                className="email-send-btn"
                onClick={handleSend}
                disabled={sending || sent}
              >
                {sending ? "Sending..." : sent ? (sentMode === "sent" ? "✓ Sent!" : "✓ Draft Saved") : "Send Email"}
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
